spring.application.name=batch
eazy.batch.enabled=true
eazy.batch.thread-pool-size=5
eazy.batch.queue-capacity=100
eazy.batch.default-chunk-size=100
eazy.batch.default-skip-limit=10

# Spring Batch Configuration
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.isolation-level-for-create=READ_COMMITTED
spring.jpa.properties.hibernate.id.optimizer.pooled.preferred=pooled-lo
spring.batch.jdbc.table-prefix=BATCH_